name: XAU 5m alert

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที (UTC)
  workflow_dispatch: {}      # ยังอนุญาตกด Run เองได้ (ไม่ส่งข้อความเทสแล้ว)

concurrency:
  group: xau-alert
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run once
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT:  ${{ secrets.TG_CHAT }}
        run: python xau_once.py
